name: Run API and Test with Newman

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.6-eclipse-temurin-17  # Optimized for Java + Maven

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        run: |
            apt-get update
            apt-get install -y nodejs npm

      - name: Build Java API
        run: mvn clean package -DskipTests

      - name: Start API Server
        run: |
          java -jar target/*.jar &
          sleep 10

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests
        run: newman run ".dev/Test Java App API.postman_collection" --env-var base_url=http://localhost:8080