name: Run API and Test with Newman

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.6-eclipse-temurin-17  # Optimized for Java + Maven

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}  # Checkout the correct branch
          fetch-depth: 0  # Ensure all files are fetched

      - name: Install Node.js 18 and npm
        run: |
          apt-get update
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt-get install -y nodejs

      - name: Build Java API
        run: mvn clean package -DskipTests

      - name: Start API Server
        run: |
          java -jar target/*.jar &
          sleep 10

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests
        run: newman run "api.postman_collection.json" --env-var base_url=http://localhost:8080/api/v1