name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ci:
    uses: ferrys-appen/cicd/.github/workflows/java-on-push-ci.yaml@main
    with:
      sonar_token: "aaaa"
