name: PR Checklist Validator
on:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PR checklist completion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body -q '.body')

          echo "PR Description:"
          echo "$PR_BODY"

          # Extract values from checklist using awk
          SUMMARY=$(echo "$PR_BODY" | awk -F': ' '/- Summary of Changes:/ {print $2}')
          DETAILS=$(echo "$PR_BODY" | awk -F': ' '/- Details of Changes:/ {print $2}')
          REVIEWERS=$(echo "$PR_BODY" | awk -F': ' '/- Code Reviewers:/ {print $2}')
          DB_CHANGES=$(echo "$PR_BODY" | awk -F': ' '/- DB Changes Needed:/ {print $2}')
          TEST_CASES=$(echo "$PR_BODY" | awk -F': ' '/- Test Case Implemented:/ {print $2}')

          # Function to check if a field is empty
          check_field() {
            FIELD_NAME=$1
            FIELD_VALUE=$2
            if [[ -z "$FIELD_VALUE" || "$FIELD_VALUE" == "N/A" ]]; then
              echo "❌ $FIELD_NAME is missing or not filled in"
              exit 1
            fi
          }

          # Validate each field
          check_field "Summary of Changes" "$SUMMARY"
          check_field "Details of Changes" "$DETAILS"
          check_field "Code Reviewers" "$REVIEWERS"
          check_field "DB Changes Needed" "$DB_CHANGES"
          check_field "Test Case Implemented" "$TEST_CASES"

          echo "✅ PR checklist is valid"
