name: PR Description Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_pr_description:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Description
        uses: actions/github-script@v7
        with:
          script: |
            const requiredFields = [
              '> - Summary of Changes:',
              '> - Details of Changes:',
              '> - Code Reviewers:',
              '> - DB Changes Needed:',
              '> - Test Case Implemented:'
            ];

            const prBody = context.payload.pull_request.body || '';
            const missingFields = requiredFields.filter(field => !prBody.includes(field));

            if (missingFields.length > 0) {
              core.setFailed(`Missing required fields in PR description:\n\n${missingFields.join('\n')}`);
            }